# Generated by Django 4.1 on 2022-08-25 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Contact Time')),
            ],
        ),
    ]
