# Generated by Django 4.1 on 2022-08-19 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zipcode', models.CharField(max_length=50, verbose_name='Zipcode')),
                ('description', models.TextField(verbose_name='Description')),
                ('sale_type', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=20, verbose_name='Sale Type')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('bedrooms', models.IntegerField(verbose_name='Bed Rooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Bath Rooms')),
                ('home_type', models.CharField(choices=[('House', 'House'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse')], default='House', max_length=20, verbose_name='Home Type')),
                ('sqft', models.IntegerField(verbose_name='Sqft')),
                ('open_house', models.BooleanField(default=False, verbose_name='Open House')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Main Product Image')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_17', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_18', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_19', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('photo_20', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='More Product Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realter')),
            ],
        ),
    ]
